
package co.com.mintrabajo.tys.adapters.integration.client.esb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JSONGenericoPortType", targetNamespace = "http://soaint.com/Servicios/Utilitario/wsdl/JSONGenerico")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JSONGenericoPortType {


    /**
     * 
     * @param input
     * @return
     *     returns co.com.mintrabajo.tys.adapters.integration.client.esb.MensajeSalidaType
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/JSONGenerico/insertarPpdDocumento")
    @WebResult(name = "MensajeSalida", targetNamespace = "http://soaint.com/Servicios/Utilitario/xsd/JSONGenerico", partName = "output")
    public MensajeSalidaType ejecutar(
        @WebParam(name = "MensajeEntrada", targetNamespace = "http://soaint.com/Servicios/Utilitario/xsd/JSONGenerico", partName = "input")
        MensajeEntradaType input);

}
