
package co.com.mintrabajo.tys.adapters.integration.client.esb;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JSONGenericoService", targetNamespace = "http://soaint.com/Servicios/Utilitario/wsdl/JSONGenerico", wsdlLocation = "file:/C:/Users/jrodriguez/Downloads/JSON Generico/JSON Generico/wsdl/JSONGenerico.wsdl")
public class JSONGenericoService
    extends Service
{

    private final static URL JSONGENERICOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.com.mintrabajo.tys.adapters.integration.client.esb.JSONGenericoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.com.mintrabajo.tys.adapters.integration.client.esb.JSONGenericoService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/jrodriguez/Downloads/JSON Generico/JSON Generico/wsdl/JSONGenerico.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/jrodriguez/Downloads/JSON Generico/JSON Generico/wsdl/JSONGenerico.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JSONGENERICOSERVICE_WSDL_LOCATION = url;
    }

    public JSONGenericoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JSONGenericoService() {
        super(JSONGENERICOSERVICE_WSDL_LOCATION, new QName("http://soaint.com/Servicios/Utilitario/wsdl/JSONGenerico", "JSONGenericoService"));
    }

    /**
     * 
     * @return
     *     returns JSONGenericoPortType
     */
    @WebEndpoint(name = "JSONGenericoSOAP")
    public JSONGenericoPortType getJSONGenericoSOAP() {
        return super.getPort(new QName("http://soaint.com/Servicios/Utilitario/wsdl/JSONGenerico", "JSONGenericoSOAP"), JSONGenericoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JSONGenericoPortType
     */
    @WebEndpoint(name = "JSONGenericoSOAP")
    public JSONGenericoPortType getJSONGenericoSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaint.com/Servicios/Utilitario/wsdl/JSONGenerico", "JSONGenericoSOAP"), JSONGenericoPortType.class, features);
    }

}
