
package co.com.mintrabajo.tys.adapters.integration.client.ecm;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentosBPMService", targetNamespace = "http://soaint.com/Servicios/Negocio/wsdl/DocumentosBPM", wsdlLocation = "http://172.20.22.202:7801/DocumentosBPMService/DocumentosBPMPort?wsdl")
public class DocumentosBPMService
    extends Service
{

    private final static URL DOCUMENTOSBPMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.com.mintrabajo.tys.adapters.integration.client.ecm.DocumentosBPMService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.com.mintrabajo.tys.adapters.integration.client.ecm.DocumentosBPMService.class.getResource(".");
            url = new URL(baseUrl, "http://172.20.22.202:7801/DocumentosBPMService/DocumentosBPMPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.20.22.202:7801/DocumentosBPMService/DocumentosBPMPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTOSBPMSERVICE_WSDL_LOCATION = url;
    }

    public DocumentosBPMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentosBPMService() {
        super(DOCUMENTOSBPMSERVICE_WSDL_LOCATION, new QName("http://soaint.com/Servicios/Negocio/wsdl/DocumentosBPM", "DocumentosBPMService"));
    }

    /**
     *
     * @return
     *     returns DocumentosBPMPortType
     */
    @WebEndpoint(name = "DocumentosBPMSOAP")
    public DocumentosBPMPortType getDocumentosBPMSOAP() {
        return super.getPort(new QName("http://soaint.com/Servicios/Negocio/wsdl/DocumentosBPM", "DocumentosBPMSOAP"), DocumentosBPMPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentosBPMPortType
     */
    @WebEndpoint(name = "DocumentosBPMSOAP")
    public DocumentosBPMPortType getDocumentosBPMSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaint.com/Servicios/Negocio/wsdl/DocumentosBPM", "DocumentosBPMSOAP"), DocumentosBPMPortType.class, features);
    }

}
