
package co.com.mintrabajo.tys.adapters.integration.client.ecm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentosBPMPortType", targetNamespace = "http://soaint.com/Servicios/Negocio/wsdl/DocumentosBPM")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentosBPMPortType {


    /**
     * 
     * @param documentosOut
     * @param strNroRadicadoIn
     * @param encabezadoEntrada
     * @param encabezadoSalida
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/DocumentosBPM/obtenerDatosDocumento")
    @RequestWrapper(localName = "obtenerDatosDocumento", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.ecm.ObtenerDatosDocumentoType")
    @ResponseWrapper(localName = "obtenerDatosDocumentoResponse", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.ecm.ObtenerDatosDocumentoResponseType")
    public void obtenerDatosDocumento(
            @WebParam(name = "EncabezadoEntrada", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA")
                    EncabezadoEntradaType encabezadoEntrada,
            @WebParam(name = "strNroRadicado_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strNroRadicadoIn,
            @WebParam(name = "EncabezadoSalida", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA", mode = WebParam.Mode.OUT)
                    Holder<EncabezadoSalidaType> encabezadoSalida,
            @WebParam(name = "documentos_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfActualizarDocumentoDTO> documentosOut);

    /**
     *
     * @param strCodigoOut
     * @param intTramiteTipologiaIn
     * @param intIdDocumentoIn
     * @param strNroRadicadoIn
     * @param strNombreDocumentoIn
     * @param strCorPlantillaIn
     * @param strIdFilenetIn
     * @param strBase64In
     * @param encabezadoEntrada
     * @param strMensajeOut
     * @param encabezadoSalida
     * @param strCodigoDependenciaIn
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/DocumentosBPM/subirDocumentoActualizar")
    @RequestWrapper(localName = "subirDocumentoActualizar", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.ecm.SubirDocumentoActualizarType")
    @ResponseWrapper(localName = "subirDocumentoActualizarResponse", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.ecm.SubirDocumentoActualizarResponseType")
    public void subirDocumentoActualizar(
            @WebParam(name = "EncabezadoEntrada", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA")
                    EncabezadoEntradaType encabezadoEntrada,
            @WebParam(name = "strCodigoDependencia_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strCodigoDependenciaIn,
            @WebParam(name = "strNroRadicado_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strNroRadicadoIn,
            @WebParam(name = "strBase64_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strBase64In,
            @WebParam(name = "intTramiteTipologia_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    int intTramiteTipologiaIn,
            @WebParam(name = "strCorPlantilla_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strCorPlantillaIn,
            @WebParam(name = "strNombreDocumento_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strNombreDocumentoIn,
            @WebParam(name = "intIdDocumento_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    int intIdDocumentoIn,
            @WebParam(name = "strIdFilenet_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strIdFilenetIn,
            @WebParam(name = "EncabezadoSalida", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA", mode = WebParam.Mode.OUT)
                    Holder<EncabezadoSalidaType> encabezadoSalida,
            @WebParam(name = "strCodigo_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", mode = WebParam.Mode.OUT)
                    Holder<String> strCodigoOut,
            @WebParam(name = "strMensaje_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", mode = WebParam.Mode.OUT)
                    Holder<String> strMensajeOut);

    /**
     *
     * @param strFileNameOut
     * @param strBase64Out
     * @param strIdFilenetIn
     * @param encabezadoEntrada
     * @param encabezadoSalida
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/DocumentosBPM/obtenerDocumentoPorIdFilenet")
    @RequestWrapper(localName = "obtenerDocumentoPorIdFilenet", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.ecm.ObtenerDocumentoPorIdFilenetType")
    @ResponseWrapper(localName = "obtenerDocumentoPorIdFilenetResponse", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.ecm.ObtenerDocumentoPorIdFilenetResponseType")
    public void obtenerDocumentoPorIdFilenet(
            @WebParam(name = "EncabezadoEntrada", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA")
                    EncabezadoEntradaType encabezadoEntrada,
            @WebParam(name = "strIdFilenet_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM")
                    String strIdFilenetIn,
            @WebParam(name = "EncabezadoSalida", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA", mode = WebParam.Mode.OUT)
                    Holder<EncabezadoSalidaType> encabezadoSalida,
            @WebParam(name = "strBase64_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", mode = WebParam.Mode.OUT)
                    Holder<String> strBase64Out,
            @WebParam(name = "strFileName_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/DocumentosBPM", mode = WebParam.Mode.OUT)
                    Holder<String> strFileNameOut);

}
