
package co.com.mintrabajo.tys.adapters.integration.client.bpm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TramitesBPMService", targetNamespace = "http://soaint.com/Servicios/Negocio/wsdl/TramitesBPM", wsdlLocation = "http://172.20.22.202:7800/TramitesBPMService/TramitesBPMPort?wsdl")
public class TramitesBPMService
    extends Service
{

    private final static URL TRAMITESBPMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(co.com.mintrabajo.tys.adapters.integration.client.bpm.TramitesBPMService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = co.com.mintrabajo.tys.adapters.integration.client.bpm.TramitesBPMService.class.getResource(".");
//            url = new URL(baseUrl, "http://172.20.22.202:7801/TramitesBPMService/TramitesBPMPort?wsdl");
            url = new URL(baseUrl, "http://172.20.22.202:7800/TramitesBPMService/TramitesBPMPort?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.20.22.202:7800/TramitesBPMService/TramitesBPMPort?wsdl', retrying as a local file");
            //logger.warning("Failed to create URL for the wsdl Location: 'http://172.20.22.202:7801/TramitesBPMService/TramitesBPMPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRAMITESBPMSERVICE_WSDL_LOCATION = url;
    }

    public TramitesBPMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TramitesBPMService() {
        super(TRAMITESBPMSERVICE_WSDL_LOCATION, new QName("http://soaint.com/Servicios/Negocio/wsdl/TramitesBPM", "TramitesBPMService"));
    }

    /**
     * 
     * @return
     *     returns TramitesBPMPortType
     */
    @WebEndpoint(name = "TramitesBPMSOAP")
    public TramitesBPMPortType getTramitesBPMSOAP() {
        return super.getPort(new QName("http://soaint.com/Servicios/Negocio/wsdl/TramitesBPM", "TramitesBPMSOAP"), TramitesBPMPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TramitesBPMPortType
     */
    @WebEndpoint(name = "TramitesBPMSOAP")
    public TramitesBPMPortType getTramitesBPMSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soaint.com/Servicios/Negocio/wsdl/TramitesBPM", "TramitesBPMSOAP"), TramitesBPMPortType.class, features);
    }

}
