
package co.com.mintrabajo.tys.adapters.integration.client.bpm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TramitesBPMPortType", targetNamespace = "http://soaint.com/Servicios/Negocio/wsdl/TramitesBPM")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TramitesBPMPortType {


    /**
     * 
     * @param strId
     * @param encabezadoEntrada
     * @param encabezadoSalida
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/TramitesBPM/actualizarDocumentoWeb")
    @RequestWrapper(localName = "actualizarDocumentoWeb", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.bpm.ActualizarDocumentoWebType")
    @ResponseWrapper(localName = "actualizarDocumentoWebResponse", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.bpm.ActualizarDocumentoWebResponseType")
    public void actualizarDocumentoWeb(
        @WebParam(name = "EncabezadoEntrada", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA")
        EncabezadoEntradaType encabezadoEntrada,
        @WebParam(name = "strId", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", mode = WebParam.Mode.INOUT)
        Holder<String> strId,
        @WebParam(name = "EncabezadoSalida", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA", mode = WebParam.Mode.OUT)
        Holder<EncabezadoSalidaType> encabezadoSalida);

    /**
     * 
     * @param input
     * @return
     *     returns co.com.mintrabajo.tys.adapters.integration.client.bpm.IniciarProcesoTySResponseType
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/TramitesBPM/iniciarProcesoTyS")
    @WebResult(name = "IniciarProcesoTySResponse", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", partName = "output")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public IniciarProcesoTySResponseType iniciarProcesoTyS(
        @WebParam(name = "IniciarProcesoTyS", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", partName = "input")
        IniciarProcesoTySType input);

    /**
     * 
     * @param strIdSeccionOut
     * @param strGradoAsociacionIn
     * @param strIdSubFondoIn
     * @param encabezadoEntrada
     * @param strIdSubFondoOut
     * @param strCodigoSeccionOut
     * @param encabezadoSalida
     * @param strCodigoTramiteIn
     */
    @WebMethod(action = "http://soaint.com/Servicios/Negocio/Administracion/wsdl/TramitesBPM/obtenerDatosSeccional")
    @RequestWrapper(localName = "obtenerDatosSeccional", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.bpm.ObtenerDatosSeccionalType")
    @ResponseWrapper(localName = "obtenerDatosSeccionalResponse", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", className = "co.com.mintrabajo.tys.adapters.integration.client.bpm.ObtenerDatosSeccionalResponseType")
    public void obtenerDatosSeccional(
        @WebParam(name = "EncabezadoEntrada", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA")
        EncabezadoEntradaType encabezadoEntrada,
        @WebParam(name = "strCodigoTramite_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM")
        String strCodigoTramiteIn,
        @WebParam(name = "strGradoAsociacion_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM")
        String strGradoAsociacionIn,
        @WebParam(name = "strIdSubFondo_in", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM")
        String strIdSubFondoIn,
        @WebParam(name = "EncabezadoSalida", targetNamespace = "http://soaint.com/Servicios/Base/EncabezadosSOA", mode = WebParam.Mode.OUT)
        Holder<EncabezadoSalidaType> encabezadoSalida,
        @WebParam(name = "strIdSeccion_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", mode = WebParam.Mode.OUT)
        Holder<String> strIdSeccionOut,
        @WebParam(name = "strCodigoSeccion_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", mode = WebParam.Mode.OUT)
        Holder<String> strCodigoSeccionOut,
        @WebParam(name = "strIdSubFondo_out", targetNamespace = "http://soaint.com/Servicios/Negocio/xsd/TramitesBPM", mode = WebParam.Mode.OUT)
        Holder<String> strIdSubFondoOut);

}
